        <?php
        
        /**
        * Sends an email to the user
        */
        function email_club_registration_email_action() {
            global $user;
            
            $from = 'mike@koumbit.org';
            $to = $user->mail;
            $language = user_preferred_language($user);
            $params = array(
                'username'      => $user->name,
                
            );
            
            drupal_mail( 'email_club_registration', 'email_pdf', $to, $language, $params, $from, $send = TRUE );
        }
        
        /**
        * Implements hook_mail()
        */
        function email_club_registration_mail( $key, &$message, $params ) {
            switch( $key ) {
                case 'email_pdf':
                    // Set headers etc
                    $message['subject'] = t('Hello');
                    $message['body'][] = t('Hello @username,', array('@username' => $params['username']));
                    $message['body'][] = t('The main part of the message.');
                    break;
            }
        }
        
