        <?php
        
        /**
        * Sends an email to the user.
        * 
        * This function was implemented to test outgoing emails from Drupal
        */
        function email_club_registration_email_action() {
            global $user;
            
            $from = 'mike@koumbit.org';
            $to = $user->mail;
            $language = user_preferred_language($user);
            $params = array(
                'username'      => $user->name,
                
            );
            
            //call the hook_mail function using the parameters provided to drupal_mail()
            drupal_mail( 'email_club_registration', 'email_pdf', $to, $language, $params, $from, $send = TRUE );
        }
        /**
        * Implements hook_mail()
        */
        function email_club_registration_mail( $key, &$message, $params ) {
            switch( $key ) {
                case 'email_pdf':
                    // Set headers etc
                    $message['subject'] = t('Hello');
                    $message['body'][] = t('Hello @username,', array('@username' => $params['username']));
                    $message['body'][] = t('The main part of the message.');
                    break;
            }
        }
        
        /**
        * Sends an email to the user using mimemail.
        * 
        * @todo add an interface for the user to put in what email to send it from
        * @todo add an interface for the user to put in what email to send it to
        * @todo add an interface for the user to put in the email subject
        * @todo add an interface for the user to put in the email body
        */
        function email_club_registration_mimemail_action() {
            //identify the email with a key
            $mailkey = 'email_pdf';
            
            //standard email parameters...to, from, subject etc
            $sender = 'mike@koumbit.org';
            $recipients[] = 'mike@koumbit.org';
            $subject = t( 'CSU club registration form' );
            $body = 'Your PDF is attached';
            
            //send in plaintext, without headers, and attach a PDF of the current node
            $plaintext = false;
            $headers = array();
            $attachments = array();
            
            //make the body into text, and decode the HTML entities to regular UTF-8 bytes.
            $text = drupal_html_to_text( decode_entities( $body ) );
            
            //send directly
            $send = true;

            mimemail( $sender, $recipients, $subject, $body, $plaintext, $headers, $text, $attachments );
        }
        
        
